// Code generated by promql-sync. DO NOT EDIT.
//
// Regenerate with:
//   cargo run -p promql-sync -- generate-grammar
//
// Source material:
//   src/promql-parser/upstream/generated_parser.y  (vendored from
//     prometheus/prometheus — see upstream/MANIFEST.toml for the
//     pinned sha)
//   src/promql-parser/grammar-actions.toml          (return types
//     + per-alt Rust action bodies, hand-maintained)
//   src/promql-parser/grammar-tokens.toml           (upstream →
//     grmtools token rename table)

%start expr
%left 'LOR'
%left 'LAND' 'LUNLESS'
%left 'EQLC' 'GTE' 'GTR' 'LSS' 'LTE' 'NEQ' 'TRIM_UPPER' 'TRIM_LOWER'
%left 'ADD' 'SUB'
%left 'MUL' 'DIV' 'MOD' 'ATAN2'
%right 'POW'
%nonassoc 'OFFSET'
%right 'LBRACKET'
%%

expr -> Result<Expr, ()>:
    aggregate_expr { $1 }
  | binary_expr { $1 }
  | function_call { $1 }
  | matrix_selector { $1 }
  | number_duration_literal { $1 }
  | offset_expr { $1 }
  | paren_expr { $1 }
  | string_literal { $1 }
  | subquery_expr { $1 }
  | unary_expr { $1 }
  | vector_selector { $1 }
  | step_invariant_expr { $1 }
  | duration_expr { $1 }
  ;

aggregate_expr -> Result<Expr, ()>:
    aggregate_op aggregate_modifier function_call_body { actions::aggregate($lexer, $span, $1?, Some($2?), $3?) }
  | aggregate_op function_call_body aggregate_modifier { actions::aggregate($lexer, $span, $1?, Some($3?), $2?) }
  | aggregate_op function_call_body { actions::aggregate($lexer, $span, $1?, None, $2?) }
  ;

aggregate_modifier -> Result<(bool, Vec<String>), ()>:
    'BY' grouping_labels { Ok((false, $2?)) }
  | 'WITHOUT' grouping_labels { Ok((true, $2?)) }
  ;

binary_expr -> Result<Expr, ()>:
    expr 'ADD' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'ATAN2' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'DIV' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'EQLC' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'GTE' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'GTR' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'TRIM_UPPER' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'TRIM_LOWER' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'LAND' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'LOR' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'LSS' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'LTE' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'LUNLESS' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'MOD' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'MUL' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'NEQ' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'POW' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  | expr 'SUB' bin_modifier expr { actions::binary($lexer, $2.map_err(|_| ())?, $1, $4) }
  ;

bin_modifier -> Result<(), ()>:
    fill_modifiers { $1 }
  ;

bool_modifier -> Result<(), ()>:
    /* empty */ { Ok(()) }
  | 'BOOL' { Ok(()) }
  ;

on_or_ignoring -> Result<(), ()>:
    bool_modifier 'IGNORING' grouping_labels { Ok(()) }
  | bool_modifier 'ON' grouping_labels { Ok(()) }
  ;

group_modifiers -> Result<(), ()>:
    bool_modifier { $1 }
  | on_or_ignoring { $1 }
  | on_or_ignoring 'GROUP_LEFT' maybe_grouping_labels { $1 }
  | on_or_ignoring 'GROUP_RIGHT' maybe_grouping_labels { $1 }
  ;

fill_modifiers -> Result<(), ()>:
    group_modifiers { $1 }
  | group_modifiers 'FILL' fill_value { $1 }
  | group_modifiers 'FILL_LEFT' fill_value { $1 }
  | group_modifiers 'FILL_RIGHT' fill_value { $1 }
  | group_modifiers 'FILL_LEFT' fill_value 'FILL_RIGHT' fill_value { Err(()) }
  | group_modifiers 'FILL_RIGHT' fill_value 'FILL_LEFT' fill_value { Err(()) }
  ;

grouping_labels -> Result<Vec<String>, ()>:
    'LPAREN' grouping_label_list 'RPAREN' { $2 }
  | 'LPAREN' grouping_label_list 'COMMA' 'RPAREN' { $2 }
  | 'LPAREN' 'RPAREN' { Ok(Vec::new()) }
  ;

grouping_label_list -> Result<Vec<String>, ()>:
    grouping_label_list 'COMMA' grouping_label { { let mut v = $1?; v.push($3?); Ok(v) } }
  | grouping_label { Ok(vec![$1?]) }
  ;

grouping_label -> Result<String, ()>:
    maybe_label { $1 }
  | 'STRING' { Ok(actions::string_literal_value($lexer, $1.map_err(|_| ())?.span())?) }
  ;

fill_value -> Result<(), ()>:
    'LPAREN' number_duration_literal 'RPAREN' { Ok(()) }
  | 'LPAREN' unary_op number_duration_literal 'RPAREN' { Err(()) }
  ;

function_call -> Result<Expr, ()>:
    'IDENT' function_call_body { actions::function_call($lexer, $span, $1.map_err(|_| ())?, $2?) }
  | at_modifier_preprocessors function_call_body { Err(()) }
  | 'STEP' function_call_body { Err(()) }
  | 'RANGE' function_call_body { Err(()) }
  ;

function_call_body -> Result<Vec<Expr>, ()>:
    'LPAREN' function_call_args 'RPAREN' { $2 }
  | 'LPAREN' 'RPAREN' { Ok(Vec::new()) }
  ;

function_call_args -> Result<Vec<Expr>, ()>:
    function_call_args 'COMMA' expr { { let mut v = $1?; v.push($3?); Ok(v) } }
  | expr { Ok(vec![$1?]) }
  | function_call_args 'COMMA' { Err(()) }
  ;

paren_expr -> Result<Expr, ()>:
    'LPAREN' expr 'RPAREN' { actions::paren($lexer, $span, $2) }
  ;

positive_duration_expr -> Result<Expr, ()>:
    duration_expr { $1 }
  ;

offset_expr -> Result<Expr, ()>:
    expr 'OFFSET' offset_duration_expr { actions::offset_from_expr($lexer, $1, $3) }
  ;

step_invariant_expr -> Result<Expr, ()>:
    expr 'AT' signed_or_unsigned_number { actions::at_timestamp_val($lexer, $1, $3?) }
  | expr 'AT' at_modifier_preprocessors 'LPAREN' 'RPAREN' { actions::at_modifier($lexer, $1, $3?) }
  ;

at_modifier_preprocessors -> Result<AtModifier, ()>:
    'START' { Ok(AtModifier::Start) }
  | 'END' { Ok(AtModifier::End) }
  ;

matrix_selector -> Result<Expr, ()>:
    expr 'LBRACKET' positive_duration_expr 'RBRACKET' { actions::matrix_selector_from_expr($lexer, $span, $1, $3) }
  ;

subquery_expr -> Result<Expr, ()>:
    expr 'LBRACKET' positive_duration_expr 'COLON' positive_duration_expr 'RBRACKET' { actions::subquery_from_exprs($lexer, $span, $1, $3, Some($5)) }
  | expr 'LBRACKET' positive_duration_expr 'COLON' 'RBRACKET' { actions::subquery_from_exprs($lexer, $span, $1, $3, None) }
  ;

unary_expr -> Result<Expr, ()>:
    unary_op expr { actions::unary_from_token($lexer, $span, $1, $2) }
  ;

vector_selector -> Result<Expr, ()>:
    metric_identifier label_matchers { actions::vector_selector($lexer, $span, Some($1?), Some($2?)) }
  | metric_identifier { actions::vector_selector($lexer, $span, Some($1?), None) }
  | label_matchers { actions::vector_selector($lexer, $span, None, Some($1?)) }
  ;

label_matchers -> Result<Vec<LabelMatcher>, ()>:
    'LBRACE' label_match_list 'RBRACE' { $2 }
  | 'LBRACE' label_match_list 'COMMA' 'RBRACE' { $2 }
  | 'LBRACE' 'RBRACE' { Ok(Vec::new()) }
  ;

label_match_list -> Result<Vec<LabelMatcher>, ()>:
    label_match_list 'COMMA' label_matcher { { let mut v = $1?; v.push($3?); Ok(v) } }
  | label_matcher { Ok(vec![$1?]) }
  ;

label_matcher -> Result<LabelMatcher, ()>:
    'IDENT' match_op 'STRING' { actions::label_matcher($lexer, $span, $1.map_err(|_| ())?.span(), $2?, $3.map_err(|_| ())?) }
  | string_identifier match_op 'STRING' { actions::label_matcher_quoted_name($lexer, $span, $1?, $2?, $3.map_err(|_| ())?) }
  | string_identifier { actions::quoted_metric_name_matcher_from_ident($lexer, $span, $1?) }
  ;

metric_identifier -> Result<String, ()>:
    'AVG' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'BOTTOMK' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'BY' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'COUNT' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'COUNT_VALUES' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'FILL' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'FILL_LEFT' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'FILL_RIGHT' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'GROUP' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'IDENT' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'LAND' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'LOR' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'LUNLESS' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'MAX' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'METRIC_IDENTIFIER' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'MIN' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'OFFSET' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'QUANTILE' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'STDDEV' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'STDVAR' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'SUM' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'TOPK' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'WITHOUT' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'START' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'END' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'LIMITK' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'LIMIT_RATIO' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'STEP' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'RANGE' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'ANCHORED' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'SMOOTHED' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  ;

aggregate_op -> Result<ItemType, ()>:
    'AVG' { Ok(ItemType::Avg) }
  | 'BOTTOMK' { Ok(ItemType::Bottomk) }
  | 'COUNT' { Ok(ItemType::Count) }
  | 'COUNT_VALUES' { Ok(ItemType::CountValues) }
  | 'GROUP' { Ok(ItemType::Group) }
  | 'MAX' { Ok(ItemType::Max) }
  | 'MIN' { Ok(ItemType::Min) }
  | 'QUANTILE' { Ok(ItemType::Quantile) }
  | 'STDDEV' { Ok(ItemType::Stddev) }
  | 'STDVAR' { Ok(ItemType::Stdvar) }
  | 'SUM' { Ok(ItemType::Sum) }
  | 'TOPK' { Ok(ItemType::Topk) }
  | 'LIMITK' { Ok(ItemType::Limitk) }
  | 'LIMIT_RATIO' { Ok(ItemType::LimitRatio) }
  ;

maybe_label -> Result<String, ()>:
    'AVG' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'BOOL' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'BOTTOMK' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'BY' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'COUNT' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'COUNT_VALUES' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'GROUP' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'GROUP_LEFT' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'GROUP_RIGHT' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'FILL' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'FILL_LEFT' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'FILL_RIGHT' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'IDENT' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'IGNORING' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'LAND' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'LOR' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'LUNLESS' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'MAX' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'METRIC_IDENTIFIER' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'MIN' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'OFFSET' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'ON' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'QUANTILE' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'STDDEV' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'STDVAR' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'SUM' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'TOPK' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'START' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'END' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'ATAN2' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'LIMITK' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'LIMIT_RATIO' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'STEP' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'RANGE' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'ANCHORED' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  | 'SMOOTHED' { Ok(actions::span_str($lexer, $1.map_err(|_| ())?.span()).to_string()) }
  ;

unary_op -> Result<ItemType, ()>:
    'ADD' { Ok(ItemType::Add) }
  | 'SUB' { Ok(ItemType::Sub) }
  ;

match_op -> Result<MatchOp, ()>:
    'EQ' { Ok(MatchOp::Equal) }
  | 'NEQ' { Ok(MatchOp::NotEqual) }
  | 'EQL_REGEX' { Ok(MatchOp::RegexEqual) }
  | 'NEQ_REGEX' { Ok(MatchOp::RegexNotEqual) }
  ;

number_duration_literal -> Result<Expr, ()>:
    'NUMBER' { actions::number_literal($lexer, $1.map_err(|_| ())?) }
  | 'DURATION' { actions::duration_literal($lexer, $1.map_err(|_| ())?) }
  ;

number -> Result<f64, ()>:
    'NUMBER' { actions::number_value($lexer, $1.map_err(|_| ())?) }
  | 'DURATION' { Err(()) }
  ;

signed_number -> Result<f64, ()>:
    'ADD' number { $2 }
  | 'SUB' number { $2.map(|v| -v) }
  ;

signed_or_unsigned_number -> Result<f64, ()>:
    number { $1 }
  | signed_number { $1 }
  ;

string_literal -> Result<Expr, ()>:
    'STRING' { actions::string_literal($lexer, $1.map_err(|_| ())?) }
  ;

string_identifier -> Result<String, ()>:
    'STRING' { Ok(actions::string_literal_value($lexer, $1.map_err(|_| ())?.span())?) }
  ;

maybe_grouping_labels -> Result<Vec<String>, ()>:
    /* empty */ { Err(()) }
  | grouping_labels { $1 }
  ;

offset_duration_expr -> Result<Expr, ()>:
    number_duration_literal { $1 }
  | unary_op number_duration_literal { actions::signed_duration($1, $2) }
  | 'STEP' 'LPAREN' 'RPAREN' { Err(()) }
  | 'RANGE' 'LPAREN' 'RPAREN' { Err(()) }
  | unary_op 'STEP' 'LPAREN' 'RPAREN' { Err(()) }
  | unary_op 'RANGE' 'LPAREN' 'RPAREN' { Err(()) }
  | min_max 'LPAREN' duration_expr 'COMMA' duration_expr 'RPAREN' { Err(()) }
  | unary_op min_max 'LPAREN' duration_expr 'COMMA' duration_expr 'RPAREN' { Err(()) }
  | unary_op 'LPAREN' duration_expr 'RPAREN' { Err(()) }
  | duration_expr { $1 }
  ;

min_max -> Result<ItemType, ()>:
    'MIN' { Err(()) }
  | 'MAX' { Err(()) }
  ;

duration_expr -> Result<Expr, ()>:
    number_duration_literal { $1 }
  | unary_op duration_expr { Err(()) }
  | duration_expr 'ADD' duration_expr { Err(()) }
  | duration_expr 'SUB' duration_expr { Err(()) }
  | duration_expr 'MUL' duration_expr { Err(()) }
  | duration_expr 'DIV' duration_expr { Err(()) }
  | duration_expr 'MOD' duration_expr { Err(()) }
  | duration_expr 'POW' duration_expr { Err(()) }
  | 'STEP' 'LPAREN' 'RPAREN' { Err(()) }
  | 'RANGE' 'LPAREN' 'RPAREN' { Err(()) }
  | min_max 'LPAREN' duration_expr 'COMMA' duration_expr 'RPAREN' { Err(()) }
  | paren_duration_expr { Err(()) }
  ;

paren_duration_expr -> Result<Expr, ()>:
    'LPAREN' duration_expr 'RPAREN' { Err(()) }
  ;

%%

use crate::ast::{AtModifier, Expr, LabelMatcher, MatchOp};
use crate::token::ItemType;
use crate::actions;
