use cfgrammar::yacc::YaccKind;
use lrlex::CTLexerBuilder;
use lrpar::CTParserBuilder;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // The PromQL grammar carries the same inherent shift/reduce
    // conflicts as upstream's goyacc grammar: one per binary operator
    // resolved by %left/%right precedence, plus a handful from the
    // postfix [range]/[range:step]/offset/@ productions. The grammar
    // uses `%expect` to opt in to that count; grmtools then accepts
    // those conflicts as designed.
    //
    // The grammar is built once, on its own, so that both lexers can
    // be generated against the same token ids: `grammar.y` has a
    // `start` rule dispatching on an injected START_* pseudo-token
    // (mirroring upstream's `parseGenerated`), and each parse mode
    // pairs it with the lexer for that mode.
    let ctp = CTParserBuilder::<lrlex::DefaultLexerTypes<u32>>::new()
        .yacckind(YaccKind::Grmtools)
        .grammar_in_src_dir("grammar.y")?
        // The emitted grammar mirrors upstream's, which is ambiguous
        // by design — operator precedence and the matrix/subquery [..]
        // productions produce a known set of shift/reduce conflicts
        // resolved by the `%left`/`%right` declarations. grmtools
        // surfaces them as warnings under this flag; goyacc accepts
        // them silently.
        .error_on_conflicts(false)
        .build()?;

    // `lexer.l` — ordinary PromQL expressions. `series.l` — series
    // descriptions (upstream's `seriesDesc` lexer mode). Neither
    // covers the whole token set on its own, and neither has a rule
    // for the START_* pseudo-tokens (those are injected in
    // `parser.rs`, never lexed), so both directions of "missing" are
    // expected.
    CTLexerBuilder::<lrlex::DefaultLexerTypes<u32>>::new()
        .rule_ids_map(ctp.token_map().clone())
        .allow_missing_terms_in_lexer(true)
        .allow_missing_tokens_in_parser(true)
        .lexer_in_src_dir("lexer.l")?
        .build()?;

    // `series.l` needs the same token to be produced from more than one
    // start condition (`IDENT` as a metric name and as a label name;
    // `LBRACE` before and after the metric name). lrlex requires rule
    // names to be unique within a file, but nothing stops two names
    // mapping to the same token id — so the extra spellings are aliased
    // here rather than distorting the grammar.
    let mut series_tokens = ctp.token_map().clone();
    for (alias, token) in [
        ("IDENT_LABEL", "IDENT"),
        ("STALE", "IDENT"),
        ("LBRACE_AFTER_NAME", "LBRACE"),
    ] {
        let id = *series_tokens
            .get(token)
            .ok_or_else(|| format!("grammar.y has no token {token} to alias {alias} onto"))?;
        series_tokens.insert(alias.to_string(), id);
    }
    CTLexerBuilder::<lrlex::DefaultLexerTypes<u32>>::new()
        .rule_ids_map(series_tokens)
        .allow_missing_terms_in_lexer(true)
        .allow_missing_tokens_in_parser(true)
        .lexer_in_src_dir("series.l")?
        .build()?;

    // The START_* pseudo-tokens are never lexed, so `parser.rs` needs
    // their ids to prepend one to the lexeme stream. Upstream reads
    // them straight off the goyacc-generated constants; we write the
    // equivalent out here.
    let mut consts = String::from(
        "// Generated by build.rs from grammar.y's token map. Token ids\n\
         // for the START_* pseudo-tokens injected by `parser.rs`.\n",
    );
    for token in [
        "START_EXPRESSION",
        "START_METRIC",
        "START_METRIC_SELECTOR",
        "START_SERIES_DESCRIPTION",
    ] {
        let id = ctp
            .token_map()
            .get(token)
            .ok_or_else(|| format!("grammar.y has no {token} token"))?;
        consts.push_str(&format!("pub const {token}: u32 = {id};\n"));
    }
    std::fs::write(
        std::path::Path::new(&std::env::var("OUT_DIR")?).join("start_tokens.rs"),
        consts,
    )?;

    Ok(())
}
