//! grmtools `.y` emitter. Given a parsed upstream goyacc grammar and
//! a [`Sidecar`], produces the text we'd write to
//! `promql-parser/src/grammar.y`.
//!
//! Emission shape (matches what `lrpar` + `cfgrammar` expect):
//!
//! ```text
//! %start StartSymbol
//! %left 'TOK1' 'TOK2'
//! %right 'TOK3'
//! %%
//!
//! RuleName -> ReturnType:
//!     'TOK' Sub { action_body }
//!   | OtherSub  { $1 }
//!   ;
//!
//! %%
//! <epilogue — Rust use statements etc.>
//! ```
//!
//! Token vs. non-terminal classification: a symbol whose name contains
//! a lowercase letter is a non-terminal. All-uppercase / underscore /
//! digit names are terminals (tokens), emitted quoted. This matches
//! both upstream's and our naming conventions.

use std::collections::{BTreeSet, VecDeque};

use anyhow::{Context, Result};

use crate::sidecar::Sidecar;
use crate::yacc::{Alternative, Assoc, Grammar, Rule};

/// Per-alt warning recorded when a mapping is missing; surfaced by the
/// CLI report so humans know what still needs hand-written actions.
#[derive(Debug)]
pub struct UnmappedAlt {
    pub rule: String,
    pub upstream_signature: String,
}

pub struct EmitResult {
    pub text: String,
    pub unmapped: Vec<UnmappedAlt>,
    pub rules_emitted: Vec<String>,
    pub rules_skipped_unreachable: Vec<String>,
}

pub fn emit(g: &Grammar, sc: &Sidecar) -> Result<EmitResult> {
    let reachable = reachable_rules(g, &sc.emit_roots, &sc.skip_rules);

    let mut out = String::new();

    // --- generation header ---
    // grmtools' yacc dialect treats `//` and `/* */` as comments, so
    // this lands intact as leading trivia and is visible to both
    // reviewers and any subsequent regeneration tooling.
    out.push_str(
        "// Code generated by promql-sync. DO NOT EDIT.\n\
         //\n\
         // Regenerate with:\n\
         //   cargo run -p promql-sync -- generate-grammar\n\
         //\n\
         // Source material:\n\
         //   promql-parser/upstream/generated_parser.y  (vendored from\n\
         //     prometheus/prometheus — see upstream/MANIFEST.toml for the\n\
         //     pinned sha)\n\
         //   promql-parser/grammar-actions.toml          (return types\n\
         //     + per-alt Rust action bodies, hand-maintained)\n\
         //   promql-parser/grammar-tokens.toml           (upstream →\n\
         //     grmtools token rename table)\n\n",
    );

    // --- preamble ---
    out.push_str(&format!("%start {}\n", sc.start_symbol));
    for p in &g.precedence {
        let kw = match p.assoc {
            Assoc::Left => "%left",
            Assoc::Right => "%right",
            Assoc::Nonassoc => "%nonassoc",
        };
        let toks: Vec<String> = p
            .tokens
            .iter()
            .map(|t| format!("'{}'", sc.rename_token(t)))
            .collect();
        out.push_str(&format!("{kw} {}\n", toks.join(" ")));
    }
    out.push_str("%%\n\n");

    // --- rules, in upstream source order ---
    let mut unmapped = Vec::new();
    let mut emitted = Vec::new();
    let mut skipped = Vec::new();
    for rule in &g.rules {
        if sc.skip_rules.iter().any(|s| s == &rule.lhs) {
            skipped.push(rule.lhs.clone());
            continue;
        }
        if !reachable.contains(&rule.lhs) {
            skipped.push(rule.lhs.clone());
            continue;
        }
        emit_rule(&mut out, rule, sc, &mut unmapped)?;
        emitted.push(rule.lhs.clone());
    }

    // --- epilogue ---
    out.push_str("%%\n\n");
    if !sc.epilogue.trim().is_empty() {
        out.push_str(sc.epilogue.trim_end());
        out.push('\n');
    }

    Ok(EmitResult {
        text: out,
        unmapped,
        rules_emitted: emitted,
        rules_skipped_unreachable: skipped,
    })
}

fn emit_rule(
    out: &mut String,
    rule: &Rule,
    sc: &Sidecar,
    unmapped: &mut Vec<UnmappedAlt>,
) -> Result<()> {
    let return_type = sc
        .return_type_for(&rule.lhs)
        .map(str::to_string)
        .unwrap_or_else(|| "Result<(), ()>".to_string());

    out.push_str(&format!("{} -> {}:\n", rule.lhs, return_type));
    // Filter alternatives that reference skipped rules or that use
    // upstream's `error` recovery production (grmtools has its own
    // error-recovery mechanism that we don't lean on, so emitting
    // `error` as a symbol would be an unknown-rule reference).
    let kept_alts: Vec<&Alternative> = rule
        .alternatives
        .iter()
        .filter(|a| {
            a.symbols
                .iter()
                .all(|s| !sc.skip_rules.iter().any(|skip| skip == s) && s != "error")
        })
        .collect();

    if kept_alts.is_empty() {
        // Should never trigger if emit_roots + skip_rules are chosen
        // consistently. Emit a placeholder so we don't leave an empty
        // rule body (which grmtools rejects).
        out.push_str(&format!(
            "    /* all alts filtered */ {{ {} }}\n  ;\n\n",
            sc.unmapped_placeholder
        ));
        unmapped.push(UnmappedAlt {
            rule: rule.lhs.clone(),
            upstream_signature: "<all alts skipped>".to_string(),
        });
        return Ok(());
    }

    for (i, alt) in kept_alts.iter().enumerate() {
        let prefix = if i == 0 { "    " } else { "  | " };
        let symbols = render_symbols(&alt.symbols, sc);
        let body = if let Some(explicit) = sc.find_action(&rule.lhs, &alt.signature()) {
            explicit.to_string()
        } else if let Some(default) = sc.default_action_for(&rule.lhs) {
            default.to_string()
        } else {
            unmapped.push(UnmappedAlt {
                rule: rule.lhs.clone(),
                upstream_signature: alt.signature(),
            });
            sc.unmapped_placeholder.clone()
        };
        if symbols.is_empty() {
            out.push_str(&format!("{prefix}/* empty */ {{ {body} }}\n"));
        } else {
            out.push_str(&format!("{prefix}{symbols} {{ {body} }}\n"));
        }
    }
    out.push_str("  ;\n\n");
    Ok(())
}

fn render_symbols(syms: &[String], sc: &Sidecar) -> String {
    syms.iter()
        .map(|s| render_symbol(s, sc))
        .collect::<Vec<_>>()
        .join(" ")
}

fn render_symbol(s: &str, sc: &Sidecar) -> String {
    if is_terminal_name(s) {
        format!("'{}'", sc.rename_token(s))
    } else {
        s.to_string()
    }
}

fn is_terminal_name(s: &str) -> bool {
    // Convention: terminals are all-uppercase/underscore/digits.
    // Anything with a lowercase letter is a non-terminal. `error`
    // (lowercase) is the one reserved non-terminal-ish symbol; it
    // should pass through unquoted because grmtools treats `error`
    // specially.
    !s.chars().any(|c| c.is_ascii_lowercase())
}

// ---------------- reachability ----------------

/// Compute the set of rule LHS names reachable from any of `roots`,
/// stopping at `skip_rules` (i.e. a skipped rule is treated as a leaf).
fn reachable_rules(g: &Grammar, roots: &[String], skip: &[String]) -> BTreeSet<String> {
    let skip_set: BTreeSet<&String> = skip.iter().collect();
    let mut reachable: BTreeSet<String> = BTreeSet::new();
    let mut queue: VecDeque<String> = VecDeque::new();
    for r in roots {
        if !skip_set.contains(r) {
            queue.push_back(r.clone());
        }
    }
    while let Some(name) = queue.pop_front() {
        if !reachable.insert(name.clone()) {
            continue;
        }
        if let Some(rule) = g.rules.iter().find(|r| r.lhs == name) {
            for alt in &rule.alternatives {
                for sym in &alt.symbols {
                    if is_terminal_name(sym) {
                        continue;
                    }
                    if sym == "error" {
                        continue;
                    }
                    if skip_set.contains(&sym.to_string()) {
                        continue;
                    }
                    if !reachable.contains(sym) {
                        queue.push_back(sym.clone());
                    }
                }
            }
        }
    }
    reachable
}

// ---------------- error-aware entry ----------------

/// Convenience: load both sidecar files and the upstream grammar from
/// `upstream_dir`, emit, and return the result. Used by the CLI.
pub fn emit_from_paths(upstream_y: &std::path::Path, sidecar: &Sidecar) -> Result<EmitResult> {
    let src = std::fs::read_to_string(upstream_y)
        .with_context(|| format!("read {}", upstream_y.display()))?;
    let g = crate::yacc::parse(&src).context("parse upstream grammar")?;
    emit(&g, sidecar)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// End-to-end: run the generator against the committed upstream
    /// grammar and committed sidecars. Catches regressions in the
    /// parser, sidecar loader, or emitter; doesn't assert the exact
    /// output (the sidecar is still being filled in) but insists on a
    /// plausibly-shaped grammar.
    #[test]
    fn regenerates_against_real_upstream() {
        let base = locate_crate_dir();
        let sc = Sidecar::load(
            &base.join("grammar-actions.toml"),
            &base.join("grammar-tokens.toml"),
        )
        .expect("load sidecars");
        let result = emit_from_paths(&base.join("upstream/generated_parser.y"), &sc).expect("emit");

        // Output leads with the DO-NOT-EDIT banner, then the grmtools
        // preamble (start + precedence), then rules.
        assert!(
            result.text.starts_with("// Code generated by promql-sync"),
            "{}",
            &result.text[..200]
        );
        assert!(result.text.contains("\n%start expr\n"));
        assert!(result.text.contains("%left"));
        assert!(result.text.contains("%%\n"));

        // Binary expression rule with operator-per-alt shape.
        assert!(
            result.text.contains("binary_expr -> Result<Expr, ()>"),
            "binary_expr rule missing or wrong return type"
        );
        assert!(result.text.contains("expr 'ADD' bin_modifier expr"));

        // At least the rules we've mapped should have emitted.
        for rule in &["expr", "binary_expr", "vector_selector", "label_matchers"] {
            assert!(
                result.rules_emitted.iter().any(|r| r == rule),
                "expected rule {rule} in emitted set"
            );
        }

        // Skip-list rules must not appear.
        for rule in &["series_description", "histogram_desc_map"] {
            assert!(
                !result.rules_emitted.iter().any(|r| r == rule),
                "rule {rule} should have been skipped"
            );
        }
    }

    fn locate_crate_dir() -> std::path::PathBuf {
        // Works whether cargo runs the test from the workspace root or
        // from the promql-sync crate directory.
        let p = std::path::PathBuf::from("../promql-parser");
        if p.exists() {
            return p;
        }
        std::path::PathBuf::from("promql-parser")
    }
}
